site_name: Netronome P4 Documentation
site_url: http://ruicunham.github.io/netronome-p4-documentation

theme: readthedocs

markdown_extensions:
  - pymdownx.superfences
  - admonition

nav:
  - Netronome:
      - Getting Started: "getting-started.md"
      - Virtual Interfaces: "vfs.md"
      - Migrating from bmv2: "bmv2.md"
      - Mac Egress CMD: "mac-cmd.md"
      - Tips and Tricks: "tips.md"
      - Useful Assets: "assets.md"
      - Replication: "replication.md"
